### ISSUE TITLE
TestAdapter shows only one executed test after upgrading to VS 2015 Update 2

### ISSUE THREAD

**Issue by bunnu** [MortenHoustonLudvigsen/KarmaTestAdapter#55]
After Upgrading to Visual Studio 2015 Update 2, the TestAdapter only shows on executed test. All other tests are displayed grey / deactivated.

Steps to reproduce:
- Update to Visual Studio 2015 Update 2
- Get TestProjects-Solution from this repository (https://github.com/MortenHoustonLudvigsen/KarmaTestAdapter/tree/master/TestProjects)
- Open solution with Visual Studio 2015 Update 2

**Comment by mstephano** [comment]
Hi bunnu, I have tried to reproduce your error (I am using Visual Studio 2013 instead of 2015), and the unit tests in TestProjects-Solution doesn't work for me, and seams to be trying to "Run All" all the time.

I fixed that by:
1. Unloading the project "KarmaRequireJasmine" from the solution
2. save the solution
3. close Visual Studio
4. re-open the solution

Now the unit tests are showing fine (8 failed and 16 passed - 24 unit test total). Can you try and tell me if it fixed your problem.

**Comment by bunnu** [comment]
Hi mstephano,

I had the same problem with the TestProject-Solution. I managed that the same way as you and have the issue as described above. Btw: An other workstation with Visual Studio 2015 Update 2 is having the same problem running karma.

**Comment by mstephano** [comment]
Sorry for not understanding well what you just said. Do you mean that you have tried my 4 steps and it did fix your problem, or it didn't fix your problem and you still see tests displayed as grey / deactivated?

**Comment by bunnu** [comment]
Hi mstephano,

I'm still having the tests displayed as grey / deactivated. For reproducing the problem I opened the TestProject-Solution. But before I could reproduce the greyed / deactivated tests, I had to unload the project 'KarmaRequireJasmine'. After that I'm getting he tests displayed grey / deactivated.

**Comment by mstephano** [comment]
Hi bunnu, I don't currently have Visual Studio 2015, but I will try to test it as soon as possible for you.

In the meantime, would you be able to test the fix I posted under https://github.com/MortenHoustonLudvigsen/JsTestAdapter/issues/2 and see if that fixes your problem?

Just to let you know, the 4 steps I said earlier for VS2013, I did them using the original KarmaTestAdapter 1.1.3, not a version that include my fix. Once I will be able to test VS2015 update 2, I will try to re-produce your issue using both version of KarmaTestAdapter (original 1.1.3 and my fix).

**Comment by branpar** [comment]
I am running VS2015 and have a similar problem in that only one test is discovered even though I have a lot of tests. Has there been any movement with this? Because it would be awesome to be able to run these in VS instead of another console window.
